#pragma once

template <class T>
class CProxy_IOSInfoControlEvents : public IConnectionPointImpl<T, &__uuidof(_IOSInfoControlEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
